import { Comfortaa, Inter } from "next/font/google";
import "./globals.css";
import Provider from "../app/utils/Provider";
const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comfortaa.variable} font-sans`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
